### PR TITLE
Flip local video stream

### PR DESCRIPTION
**Pull request by amirsanni**
Fix the wrong display of the local video stream. There is a caveat to this fix. 

If screen sharing is enabled, the user's screen will be flipped RTL. This is why I added a separate class for flipping the stream. The class can be toggled based on the current media the user is streaming. 

If user is sharing video, the class will be added. If user is sharing screen, the class will be removed.

### CODE REVIEW

**Comment by QVDev** [comment]
@amirsanni Is this a specific thing mozilla thing?

**Comment by amirsanni** [comment]
Not specific to Mozilla. It's all browsers as far as I know.

Amir Sanni

**Comment by QVDev** [comment]
can we have a before and after screenshot so its easier to see what the end result is?

**Comment by QVDev** [comment]
flip
current

Seems this PR makes it flipped what I am sending out is now different that what I receive. At least what I see.

So I am sending L R but the other one receive R L its mirrored I dont see why we would like todo this?

**Comment by QVDev** [comment]
Due to inactivity in answer I am closing this. Please feel free to add comments and we can always reopen it

**Comment by Dletta** [comment]
@QVDev 
Adding information I discovered from zoom feature request forum:
>Interestingly, the video feed mirroring was found here. It looks like what the users wanted was to not mirror their own view of themselves, but mirror the view going out to others for dance classes, school instruction (aka written words or whiteboard would show mirror to people viewing the video)
https://devforum.zoom.us/t/broadcast-of-mirror-image/208/10

But looks like the before image is already showing

**Pull request closed without merging**
