### PR TITLE
Refactor presence list and reduce gun instances to 1 in the app

### PR DESCRIPTION
**Pull request by QVDev**
Only available when in the room and by default hidden. Also this reduces the Gun instances from 3 to 1 in the app, so better maintainable.

see glitch version here:
https://meething-webrtc-qvdev.glitch.me/?room=qvdev

### CODE REVIEW

**Comment by QVDev** [comment]
Sorry for the format changes it makes it bigger than it should be

**Comment by jabis** [comment]
Oh noting the presence reports, on frontpage:
image

**Comment by QVDev** [comment]
@jabis Thanks that should not happen thats why I make an error log. I will have a look into this as it should fixed.

**Comment by QVDev** [comment]
@jabis How did you replicate this? I was not able to replicate the issue with privacy data coming trough let me know

**Comment by amark** [comment]
@QVDev @jabis yeah I'm working on some better room management or (at least) expiry mechanisms that I'll dirtily hack into GUN. I hope I don't regret this in future, haha. But this is a pretty compelling use case others have had before, and time/need/demand for it here, might as well bite the bullet.

**Comment by lmangani** [comment]
@amark right now the room leverages an actual isolation mechanism by path through [multisocket-gun](https://github.com/meething/gundb-multisocket) we would love to have your comments about this approach!

**Comment by amark** [comment]
I'm glad you're able to figure something out before I've been able to get to it myself, and I think you should keep rolling with it.

What you proposed the other day tho represented a use case others have asked about in past, and is now urgent here, so I think it is worth I spend follow-up time on it meanwhile in parallel.

My comments are biased relative to goals I have that networking, data, security (etc.) layers do not have knowledge of each other. Example: Some newcomers in chat ask "how do I keep my data secure and only sync with peers I trust?" where I argue that creates brittle networks, versus if your data is secure, it should not matter who/where it syncs or is stored. If our goal here is a presence list, which should be data (state), but it is hard to do (because tombstones pile up, etc.), I'd hope to not force all devs to have to go to a networking layer to get around that. Instead, I'd hope that you'd get this type of isolation just by stating what data you want, regardless of what peers you are connected via. In fact, as you know, at some point my hope is that people don't even specify a peer when they instantiate GUN, it just auto rotates connecting through variety of peers & DHT of those peers. So the network layer can constantly "spin" without a developer having to worry about "am I still isolated?".

Brainstorming with community yesterday we thought up a unique way to handle deletes without tombstones which we'd never thought of in prior 5 years :P so I'm hoping to try and hack that in and see how ugly/clean the implementation will be. If you're up for it, it'd be cool to then see if it would make for a better presence capability.

**Comment by lmangani** [comment]
@amark sounds awesome and looking forward to any non-workaround method in pure Gun anytime

**Comment by QVDev** [comment]
@amark thanks indeed for the feedback and indeed would be great to have something like this inside gun. @lmangani and @amark this is nothing related to separate the room. This is just making sure we dont have multiple Gun() instances going on. And that for every presence we use the correct https://github.com/meething/gundb-multisocket and make sure we dont have a lobby room anymore as it does not make sense.

**Pull request merged**
