### PR TITLE
WIP: Screen sharing start #10

### PR DESCRIPTION
**Pull request by jabis**
Hi @QVDev @lmangani, 

I started on the screen sharing ( #10 ) thing here with native `confirm`-box, would need buttons or something for toggling between, and a method for replacing the stream with shared screen/video, but I think I managed a good starting point for it.

Also noted On mobile chrome (android) I can't get the click addEventListener's to invoke, tried one old trick (onTouch-patch there) but didn't work.

Feel free to comment and enhance :)

BR,
Jabis

image

### CODE REVIEW

**Comment by jabis** [comment]
Also sidenote, I enabled fullscreen mode when clicking other party stream :)

**Comment by lmangani** [comment]
Faith in humanity restored! @jabis thank you so much for your efforts and contribution here!
Shall we add controls to switch to the mode or other items? How can we help best here?

**Comment by jabis** [comment]
@lmangani Yeah I see there are some bugs, like repetitive asking if share the screen, and firefox doesn't seem to think that the confirm box is a user interaction (bitching about it in console) have a looksie and test it, and see what would be the best place for this. I'ven't written webrtc-stuff in ages, especially in JS, so don't really have a good grasp what's supposed to happen where :)

**Comment by jabis** [comment]
I can't seem - for the life of me - figure out how to swap the screen-streams for connected users, so I'd think that's the nr.1 priority here

**Comment by lmangani** [comment]
@jabis Not sure I understand but I think the screen sharing should be simply an additional stream from an existing and labeled as such? Or did you want it to replace the existing video?

**Comment by jabis** [comment]
@lmangani well my first iteration is that you decide whether you want to share screen or regular camera, but for sure it's supposed to replace the camera when you click screenshareing and vice versa.

**Comment by jabis** [comment]
Now of course every time anyone joins it's prompting you for `screensharing?` confirm box, but yes the target is to have 2 streams and interchangeable and visible to all connected peers

**Comment by jabis** [comment]
To be more clear, you have the `Start screen sharing` in Zoom, and when you stop screen sharing it returns your video/audio stream default back - so that's the target here

**Comment by mnzaki** [comment]
In Zoom I think it actually depends on what view mode you use. whether you see "active speaker" or you see all streams.
Thing is: it's very useful to have both the screenshare stream and speaker stream, for when there's some sort of presentation and you want to see the speaker and also the screen they are sharing!

(PS awesome work so far, loving this)

**Comment by jabis** [comment]
@mnzaki yes I'm talking here about the user action "start screen share" to display to others, own video I can just set src to the stream, but I can't see how to broadcast the change to other users without them having to refresh, and then having to answer confirm boxes to screenshare again and again (re-establishing full connection) :) this seems to be because where the party-names are they are not the RTCPeerConnections but only their id's so there should be a method to renegotiate or something so that switching the stream won't just freeze on other end. Don't know how to explain in more detail. Also as firefox demands user interaction to start screensharing, the automatization doesn't seem to work without repeated sdpoffers - which is of course a pita, having confirm-boxes multiply >.< Hopefully I have more time upcoming week to look into this in more detail, but if @lmangani or @QVDev can further/ make the implementation more sane meanwhile - I am more than happy.

**Comment by lmangani** [comment]
@jabis I merged in the live changes from the glitch version, could you take a quick peek at the conflicts?

**Comment by jabis** [comment]
@lmangani I'll pull the changes and have a looksie, seems you moved stuff around quite a bit, so resolving conflicts from gh would not be fruitful :)

**Comment by lmangani** [comment]
My apologies :( We livecode this on glitch and the master diverged quite a bit, quite fast

**Comment by jabis** [comment]
@lmangani no worries, I refactored and left TODO's and comments in the code - up to date now

**Comment by lmangani** [comment]
This example provides a couple of clean methods we could get inspired by: https://github.com/tsahilevi/webrtc-missing-codelab/blob/master/static/index.html

**Comment by jabis** [comment]
@lmangani @QVDev I implemented the screen sharing and replaceTrack logic, and checked it works on my end. Can you check it works for you guys :)

**Comment by lmangani** [comment]
@jabis you are awesome! I sent you an invite to chat on gtalk if you use that
@QVDev do you know how to attach a branch to a glitch instance for testing this in parallel?

**Comment by jabis** [comment]
@lmangani you can reach me in gun gitter channel or discord - same nick ^^ :)

**Comment by jabis** [comment]
Oh ps. didn't see any hangouts invitation :O

**Comment by lmangani** [comment]
Could we rebase this to `master` so we can merge it?

**Comment by jabis** [comment]
I'll try to have some time in the evening to rebase this, and add the `pc.onnegotiationneeded` fix for at least chrome-firefox throw there. Will ping you later.

**Comment by lmangani** [comment]
@jabis thanks i tried to implement the `onnegotiationneeded`  hack for Chrome, but i got more issues than improvements so far. Happy to help if you think I can :)

**Comment by jabis** [comment]
Here's an example how the peer negotiations *should* work - it's a chore of course to make multi-party-ed, but show's parallel execution of streams without onnegotiationneeded firing multiple times causing the throw :)   https://jsfiddle.net/yxbLvjm6/29/

**Comment by jabis** [comment]
With callback-hell that would look a bit different, but the main point is nulling the handler and resetting it after all the descriptions are set and negotiation done
image

**Comment by jabis** [comment]
resetting the onn could be in the try-catch-finally to make sure the proper exec cycle is obeyed

**Pull request merged**
